-- 코드를 입력하세요
SELECT
    b.BOOK_ID,
    TO_CHAR(b.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM book b
WHERE b.CATEGORY = '인문'
  AND b.PUBLISHED_DATE >= DATE '2021-01-01'
  AND b.PUBLISHED_DATE <  DATE '2022-01-01'
ORDER BY b.PUBLISHED_DATE;